sudo: required
services:
  - docker

before_install:
  - docker build -t yassir2s/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yassir2s/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-west-1-023264199759"
  backet_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
